timezone: Europe/Berlin
highlighter: pygments
markdown: redcarpet
permalink: /auvblog4/:title

redcarpet:
  extensions: [autolink]

exclude: [README.md, TODO.md, LICENSE, node_modules, Makefile, Gulpfile.js, package.json]

# own settings
name: minddust
domain: minddust.com
url: http://www.minddust.com
description: Portfolio website of Stephan Groß
copyright: 2013&mdash;2015
author:
    name: Stephan Groß
    github_link: https://github.com/minddust
    twitter_link: https://twitter.com/minddust
